# Data Source
spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.me-dubai-1.oraclecloud.com))(connect_data=(service_name=ge1b67438db6779_evt2lh3ukndwrfms_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ADMIN
spring.datasource.password=68@N@YNxb8u_!Mb
spring.datasource.driver.class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
